language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository

before_install:
 - chmod + x gradlew

script:
    - cd gsyVideoPlayer
    - ../gradlew assembleRelease